Ietf110 feedback
irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport pull request #63
Opened 2021-03-22 17:26 UTC by NicoKos

2021-03-23 15:12 UTC, mwelzl requested changes
Many small language suggestions, and one very small thing that I hated  :-)   I hope you'll agree to remove it  :)

2021-03-23 15:12 UTC, mwelzl commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +	<t>The decoding scheme may not be able to decode all the symbols. The chance of not decoding the erased packets is a result of the size of the encoding window, the coding rate and the distribution o
```suggestion
	<t>The decoding scheme may not be able to decode all the symbols. The chance of decoding the erased packets depends on the size of the encoding window, the coding rate and the distribution of erasure in the transmission channel. The FEC channel may enable the transmission of information related to the need of supplementary symbols to adapt the level of reliability. Partial and full reliability could be envisioned.<list style="symbols">
```

2021-03-23 15:12 UTC, mwelzl commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +			<t>Full reliability: The receiver may hold symbols until the decoding of source packets is possible. In particular, if the codec does not enable a subset of the linear system to be inverted, the r
I don't get this "the minimum amount" - what minimum amount? "a pre-defined minimum amount", perhaps?

Maybe:

"If the codec does not enable a subset of the linear system to be inverted, the receiver would have to wait for a certain minimum amount of repair packets before it can recover all the source packets."

2021-03-23 15:12 UTC, mwelzl commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +			<t>Partial reliability: The receiver may deliver the packets that could have been decoded to the upper layer. Source packets that could not be decoded would be lost. If the size of the encoding wi
I think that talking about "packets" as the thing that's handed to the upper layer is confusing - especially when you then say "would be lost" - if I think of a lost packet, I think of TCP's cwnd reaction!   Maybe the first two sentences should say "data" instead of "packet" ?

2021-03-23 15:12 UTC, mwelzl commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +				<t><xref target="RFC8095"></xref> describes the mechanisms provided by existing IETF protocols such as TCP, SCTP or RTP. <xref target="RFC8406"></xref> describes the variety of coding techniques.
I would strike "a lot", it sounds a bit too colloquial to me

2021-03-23 15:12 UTC, mwelzl commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +				<t>Appendix C of <xref target="RFC8681"></xref> describes different possible parameter derivation on how to tune the parameters for target use-case. However, this discussion does not integrate co
```suggestion
				<t>Appendix C of <xref target="RFC8681"></xref> describes how to tune the parameters for target use-case. However, this discussion does not integrate congestion-controlled end points.</t>
```

2021-03-23 15:12 UTC, mwelzl commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +					<t>Recovering lost symbols may hide congestion losses from the congestion control. Disambiguate acked packets from rebuilt packets would help the sender adapts its sending rate accordingly. Ther
```suggestion
					<t>Recovering lost symbols may hide congestion losses from the congestion control. Disambiguating acked packets from rebuilt packets would help the sender adapts its sending rate accordingly. There are opportunities for introducing interaction between congestion control and coding schemes to improve the quality of experience while guaranteeing fairness with other flows.</t>
```

2021-03-23 15:12 UTC, mwelzl commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +					<t>As one example, a sender may adapt different reduction multiplier for recovered packets and lost packets, such as proposed for ECN-marked packets and lost packets in <xref target="RFC8511"></
Nooooo I think that's a bad idea!  PLEASE remove it.  Whether we were able to recover data or not means nothing about the network, but the reduction behavior should depend on the network alone.

2021-03-23 16:29 UTC, NicoKos commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +			<t>Full reliability: The receiver may hold symbols until the decoding of source packets is possible. In particular, if the codec does not enable a subset of the linear system to be inverted, the r
Will commit with your proposed text ! Thanks.

2021-03-23 16:32 UTC, NicoKos commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +			<t>Partial reliability: The receiver may deliver the packets that could have been decoded to the upper layer. Source packets that could not be decoded would be lost. If the size of the encoding wi
I think we should stick with "source packets" and propose the following: 
"The receiver cannot deliver source packets that could not have been decoded to the upper layer"

2021-03-23 16:33 UTC, NicoKos commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +				<t><xref target="RFC8095"></xref> describes the mechanisms provided by existing IETF protocols such as TCP, SCTP or RTP. <xref target="RFC8406"></xref> describes the variety of coding techniques.
OK for me

2021-03-23 16:38 UTC, NicoKos commented on draft-irtf-nwcrg-coding-and-congestion-07.xml
> +					<t>As one example, a sender may adapt different reduction multiplier for recovered packets and lost packets, such as proposed for ECN-marked packets and lost packets in <xref target="RFC8511"></
Removed in the next commit.

2021-03-23 16:40 UTC, NicoKos commented
I agree with all your comments. I think we could have a chat at  some point to discuss the sentence that has been deleted.

2021-03-23 16:55 UTC, mwelzl commented
Cool. About discussing: anytime!

2021-03-23 17:07 UTC, NicoKos commented
@mwelzl  @elochin @francoismichel : what do you think of this PR ?

2021-03-24 07:22 UTC, mwelzl approved these changes

2021-03-24 07:22 UTC, mwelzl commented
I like the PR and I agree with you. Others?

2021-03-28 12:54 UTC, elochin approved these changes

2021-03-28 12:55 UTC, elochin approved these changes

2021-03-28 12:56 UTC, elochin approved these changes

2021-03-28 12:56 UTC, elochin approved these changes

2021-03-28 12:56 UTC, elochin approved these changes

2021-03-28 12:57 UTC, elochin approved these changes

2021-03-28 12:57 UTC, elochin approved these changes

2021-03-28 12:57 UTC, elochin approved these changes

2021-03-28 12:58 UTC, elochin approved these changes

2021-03-28 12:59 UTC, elochin commented
Fine for me

2021-03-29 06:39 UTC, merged